{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.hongyu",
    "module": "oas3-redoc-spring-boot-starter",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "gum53rrp7fe2hc4s5zwdbf75ya"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-ui",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "oas3-redoc-spring-boot-starter-0.0.1.jar",
          "url": "oas3-redoc-spring-boot-starter-0.0.1.jar",
          "size": 13926,
          "sha512": "5e1284f0533b7427341859cced653aad11b1d17aa2dd58f3675cbc6041845807fd4c968918c96a6c8e7922fee930be25f727c2e284817279412d2a4322ef64ae",
          "sha256": "2ade06400ebb384aa25f4e0ded9e908bf7ce4d9175fbe37349eaee4e75e658b5",
          "sha1": "05cafc68c9bf3c5644195b6a872a9c1c33f3d092",
          "md5": "6be7a534dec7e2c934795da7cef5eeae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.0.5.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "enforced-platform"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-ui",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "oas3-redoc-spring-boot-starter-0.0.1.jar",
          "url": "oas3-redoc-spring-boot-starter-0.0.1.jar",
          "size": 13926,
          "sha512": "5e1284f0533b7427341859cced653aad11b1d17aa2dd58f3675cbc6041845807fd4c968918c96a6c8e7922fee930be25f727c2e284817279412d2a4322ef64ae",
          "sha256": "2ade06400ebb384aa25f4e0ded9e908bf7ce4d9175fbe37349eaee4e75e658b5",
          "sha1": "05cafc68c9bf3c5644195b6a872a9c1c33f3d092",
          "md5": "6be7a534dec7e2c934795da7cef5eeae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oas3-redoc-spring-boot-starter-0.0.1-sources.jar",
          "url": "oas3-redoc-spring-boot-starter-0.0.1-sources.jar",
          "size": 5119,
          "sha512": "2d07e52c2ef441674d0081219e3f26a803b966da45cab4afc04dfa9cb15cfc38405e5050c8a64b657ef5cee407e7858c040c9f492d44c66e562ceb1219b412e2",
          "sha256": "05530b46e933aebfdf5883ee3fff47c7736181e9ac302a301449eb25b8b0c14d",
          "sha1": "45691565c2318f3e137e509d480074ff4fdd0d67",
          "md5": "fbcf538c396a08c8a78848b20c7c9d95"
        }
      ]
    }
  ]
}
