{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.hongyu",
    "module": "oas3-redoc-spring-boot-starter",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "cpflwkt6hzbf7guvmcv7kiawyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-ui",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "oas3-redoc-spring-boot-starter-0.0.1.jar",
          "url": "oas3-redoc-spring-boot-starter-0.0.1.jar",
          "size": 14171,
          "sha512": "d1874d2294138c4f808cc98d778291d35f8725f8dd0d31dc0a00281610f2cca3895da10e4a58f24b75ac92a33849b813c6f72a3d94aa7d95cccf6817edb7ea74",
          "sha256": "1ceede9f6b8e3fe6b305a2f8903d9014855d986ae9b2d2f0900bdd2905293a07",
          "sha1": "260f229deab966e8c9df03d2dead5b137358f5f7",
          "md5": "bfb0b505a10ef26944d9c865dc2e35b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-dependencies",
          "version": {
            "requires": "2.0.5.RELEASE"
          },
          "attributes": {
            "org.gradle.category": "enforced-platform"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.springdoc",
          "module": "springdoc-openapi-ui",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "oas3-redoc-spring-boot-starter-0.0.1.jar",
          "url": "oas3-redoc-spring-boot-starter-0.0.1.jar",
          "size": 14171,
          "sha512": "d1874d2294138c4f808cc98d778291d35f8725f8dd0d31dc0a00281610f2cca3895da10e4a58f24b75ac92a33849b813c6f72a3d94aa7d95cccf6817edb7ea74",
          "sha256": "1ceede9f6b8e3fe6b305a2f8903d9014855d986ae9b2d2f0900bdd2905293a07",
          "sha1": "260f229deab966e8c9df03d2dead5b137358f5f7",
          "md5": "bfb0b505a10ef26944d9c865dc2e35b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oas3-redoc-spring-boot-starter-0.0.1-sources.jar",
          "url": "oas3-redoc-spring-boot-starter-0.0.1-sources.jar",
          "size": 5138,
          "sha512": "5792d53263657405093cd4b17922c9852f0f50865600a0e69ac588f4bb0715d6a1599dd2d128534bd13f9b6ac8d1493e244e2607990ebab0dbf45c8feedb2646",
          "sha256": "19cc71781635a25690260042deef9f750db87dec1cbd9e07511ff7082e7f88b1",
          "sha1": "877fe0601ff1531a012623863d0d36fbf8bab1f0",
          "md5": "d93a12414ec2cd3a215e761de2da01fb"
        }
      ]
    }
  ]
}
